#define AUDIO_BUFFER_IN         SDRAM_DEVICE_ADDR
#define AUDIO_BLOCK_SIZE        (512U)
#define AUDIO_1S_BUFFER_SIZE    (DEFAULT_AUDIO_IN_FREQ)
#define NUM_OF_AUDIO_BLOCKS     (AUDIO_1S_BUFFER_SIZE / AUDIO_BLOCK_SIZE)